AWSTemplateFormatVersion: "2010-09-09"
Description: A sample CloudFormation template with metadata
Metadata:
  Name: Vald
  Role: Solutions Architect
Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String

Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: Web_Key

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh to client host
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 192.17.0.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.17.0.0/24
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: InstanceRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: InstanceProfile
      Path: "/"
      Roles:
      - !Ref InstanceRole

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
            - InstanceProfile
            - Arn
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: 30
              VolumeType: gp2
              DeleteOnTermination: true 
              Encrypted: true 
            DeviceName: /dev/sdk
        Monitoring:
          Enabled: true
        ImageId: ami-074c4cd998e5b31fa
        InstanceType: t2.micro
        KeyName: Web_Key
        SecurityGroupIds:
        - !Ref SecurityGroup

  myServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet1"
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet2"
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: "1"
      MaxSize: '4'
      MinSize: '1'
      DesiredCapacity: '2'
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
      - Fn::ImportValue: !Sub "${EnvironmentName}-TG"