AWSTemplateFormatVersion: "2010-09-09"
Description: A sample CloudFormation template with metadata
Metadata:
  Name: Vald
  Role: Solutions Architect

Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String

Resources:
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      Name: MyTargets
      TargetType: instance
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh to client host
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet1"
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet2"

  ALBlistener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: "HTTP"

Outputs:
  WebsiteURL:
    Description: URL for ALD
    Value:
      Fn::Join:
        - ''
        - - http://
          - Fn::GetAtt:
              - MyLoadBalancer
              - DNSName

  MyTargetGroupOutput:
    Description: Target group Arn
    Value: !Ref MyTargetGroup
    Export:
      Name:
        !Sub "${EnvironmentName}-TG"
